BEGIN;

INSERT INTO asset (symbol, name, description) VALUES
('VOO', 'Vanguard S&P 500 ETF', 'Vanguard S&P 500 ETF that tracks the S&P 500 index'),
('ARM', 'Arm Holdings PLC', 'Semiconductor and software design company'),
('LIN', 'Linde PLC', 'World''s largest industrial gas company by market share and revenue'),
('AZN', 'AstraZeneca PLC', 'British-Swedish multinational pharmaceutical and biotechnology company'),
('BKR', 'Baker Hughes Co', 'International industrial service company and one of the world''s largest oil field services companies'),
('AVGO', 'Broadcom Inc', 'Designer, developer, and global supplier of semiconductor and infrastructure software products'),
('BIIB', 'Biogen Inc', 'American multinational biotechnology company'),
('BKNG', 'Booking Holdings Inc', 'Provider of online travel and related services'),
('CDNS', 'Cadence Design Systems Inc', 'Computational software company'),
('ADBE', 'Adobe Inc.', 'American multinational computer software company'),
('CHTR', 'Charter Communications Inc', 'American telecommunications and mass media company'),
('CPRT', 'Copart Inc', 'Provider of online vehicle auction and remarketing services'),
('CSGP', 'CoStar Group Inc', 'Provider of information, analytics, and marketing services to the commercial property industry'),
('CRWD', 'CrowdStrike Holdings Inc', 'American cybersecurity technology company'),
('CTAS', 'Cintas Corp', 'American corporation that provides specialized services to businesses'),
('CSCO', 'Cisco Systems Inc', 'American multinational technology conglomerate'),
('CMCSA', 'Comcast Corp', 'American telecommunications conglomerate'),
('COST', 'Costco Wholesale Corp', 'American multinational corporation which operates a chain of membership-only warehouse clubs'),
('CSX', 'CSX Corp', 'American holding company focused on rail transportation and real estate in North America'),
('CTSH', 'Cognizant Technology Solutions Corp', 'American multinational information technology services and consulting company'),
('DDOG', 'Datadog Inc', 'Monitoring and security platform for cloud applications'),
('DXCM', 'Dexcom Inc', 'Company that develops, manufactures, and distributes continuous glucose monitoring systems'),
('FANG', 'Diamondback Energy Inc', 'Independent oil and natural gas company'),
('DLTR', 'Dollar Tree Inc', 'American multi-price-point chain of discount variety stores'),
('EA', 'Electronic Arts', 'American video game company'),
('ON', 'ON Semiconductor Corp', 'American semiconductor supplier company'),
('EXC', 'Exelon Corp', 'American Fortune 100 energy company'),
('TTD', 'Trade Desk Inc', 'Technology company that markets a software platform used by digital ad buyers'),
('FAST', 'Fastenal Co', 'American company that distributes industrial, safety, and construction supplies'),
('GFS', 'GlobalFoundries Inc', 'Multinational semiconductor contract manufacturing and design company'),
('META', 'Meta Platforms Inc', 'American multinational technology conglomerate'),
('FI', 'Fiserv Inc', 'American multinational Fortune 500 company that provides financial technology services'),
('FTNT', 'Fortinet Inc', 'American multinational corporation that develops and markets cybersecurity solutions'),
('GILD', 'Gilead Sciences Inc', 'American biopharmaceutical company'),
('GOOG', 'Alphabet Class C', 'Multinational technology conglomerate holding company'),
('GOOGL', 'Alphabet Class A', 'Multinational technology conglomerate holding company'),
('HON', 'Honeywell International Inc', 'American multinational conglomerate corporation'),
('ILMN', 'Illumina Inc', 'American company that develops, manufactures, and markets integrated systems for large-scale analysis of genetic variation and function'),
('INTC', 'Intel Corp', 'American multinational corporation and technology company'),
('INTU', 'Intuit Inc', 'American business software company that specializes in financial software'),
('ISRG', 'Intuitive Surgical Inc', 'American corporation that develops, manufactures, and markets robotic products designed to improve clinical outcomes of patients'),
('MRVL', 'Marvell Technology Inc', 'American company that develops and produces semiconductors and related technology'),
('IDXX', 'IDEXX Laboratories Inc', 'American multinational corporation that develops, manufactures, and distributes products and services for the companion animal veterinary, livestock and poultry, water testing, and dairy markets'),
('KDP', 'Keurig Dr Pepper Inc', 'American beverage company'),
('KLAC', 'KLA Corp', 'American corporation that supplies process control and yield management systems for the semiconductor industry'),
('KHC', 'Kraft Heinz Co', 'American food company formed by the merger of Kraft Foods and Heinz'),
('LRCX', 'Lam Research Corp', 'American corporation that engages in the design, manufacture, marketing, and service of semiconductor processing equipment used in the fabrication of integrated circuits'),
('LULU', 'Lululemon Athletica Inc', 'Canadian athletic apparel retailer'),
('MELI', 'MercadoLibre Inc', 'Argentine company incorporated in the United States that operates online marketplaces dedicated to e-commerce and online auctions'),
('MAR', 'Marriott International Inc', 'American multinational company that operates, franchises, and licenses lodging including hotel, residential, and timeshare properties'),
('MCHP', 'Microchip Technology Inc', 'American manufacturer of microcontroller, mixed-signal, analog and Flash-IP integrated circuits'),
('MDLZ', 'Mondelez International Inc', 'American multinational confectionery, food, and beverage company'),
('MRNA', 'Moderna Inc', 'American pharmaceutical and biotechnology company'),
('MNST', 'Monster Beverage Corp', 'American beverage company that manufactures energy drinks'),
('MSFT', 'Microsoft Corp', 'American multinational technology corporation'),
('MU', 'Micron Technology Inc', 'American producer of computer memory and computer data storage'),
('NFLX', 'Netflix Inc', 'American technology and media services provider and production company'),
('GRAL', 'Grail Inc', 'Healthcare company focused on early cancer detection'),
('NVDA', 'NVIDIA Corp', 'American multinational technology company'),
('NXPI', 'NXP Semiconductors NV', 'Dutch semiconductor designer and manufacturer'),
('ODFL', 'Old Dominion Freight Line Inc', 'American regional and national LTL motor carrier'),
('ORLY', 'O''Reilly Automotive Inc', 'American auto parts retailer'),
('PCAR', 'Paccar Inc', 'American Fortune 500 company and technology company'),
('PANW', 'Palo Alto Networks Inc', 'American multinational cybersecurity company'),
('PAYX', 'Paychex Inc', 'American provider of human resource, payroll, and benefits outsourcing services'),
('PDD', 'PDD Holdings Inc', 'Multinational commerce group'),
('PYPL', 'PayPal Holdings Inc', 'American company operating an online payments system'),
('PEP', 'PepsiCo Inc.', 'American multinational food, snack, and beverage corporation'),
('QCOM', 'Qualcomm Inc', 'American multinational corporation that creates semiconductors, software, and services related to wireless technology'),
('REGN', 'Regeneron Pharmaceuticals Inc', 'American biotechnology company'),
('ROST', 'Ross Stores Inc', 'American chain of discount department stores'),
('SBUX', 'Starbucks Corp', 'American multinational chain of coffeehouses and roastery reserves'),
('SNPS', 'Synopsys Inc', 'American electronic design automation company'),
('TSLA', 'Tesla Inc', 'American multinational automotive and clean energy company'),
('TXN', 'Texas Instruments Inc', 'American technology company that designs and manufactures semiconductors'),
('TMUS', 'T-Mobile US Inc', 'American wireless network operator'),
('VRSK', 'Verisk Analytics Inc', 'American data analytics and risk assessment firm'),
('VRTX', 'Vertex Pharmaceuticals Inc', 'American biopharmaceutical company'),
('WBD', 'Warner Bros Discovery Inc', 'American multinational mass media and entertainment conglomerate'),
('WDAY', 'Workday Inc', 'American on‑demand financial management and human capital management software vendor'),
('XEL', 'Xcel Energy Inc', 'American utility holding company'),
('ZS', 'Zscaler Inc', 'American cloud security company'),
('ADP', 'Automatic Data Processing Inc', 'American provider of human resources management software and services'),
('ABNB', 'Airbnb Inc', 'American company that operates an online marketplace for lodging'),
('AMD', 'Advanced Micro Devices Inc', 'American multinational semiconductor company'),
('CEG', 'Constellation Energy Corp', 'American fortune 500 energy company'),
('AMZN', 'Amazon.com Inc', 'American multinational technology company'),
('AMGN', 'Amgen Inc', 'American multinational biopharmaceutical company'),
('AEP', 'American Electric Power Company Inc', 'American electric utility company'),
('CDW', 'CDW Corp', 'American provider of technology products and services for business, government and education'),
('CCEP', 'Coca-Cola Europacific Partners PLC', 'British multinational bottling company'),
('ADI', 'Analog Devices Inc', 'American multinational semiconductor company'),
('MDB', 'MongoDB Inc', 'American software company'),
('DASH', 'DoorDash Inc', 'American food delivery service'),
('ROP', 'Roper Technologies Inc', 'American diversified industrial company'),
('ANSS', 'ANSYS Inc', 'American company that develops and markets multiphysics engineering simulation software'),
('AAPL', 'Apple Inc', 'American multinational technology company'),
('AMAT', 'Applied Materials Inc', 'American corporation that supplies equipment, services and software for the manufacture of semiconductor chips'),
('GEHC', 'GE Healthcare Technologies Inc', 'American multinational medical technology company'),
('ASML', 'ASML Holding NV', 'Dutch multinational company and the largest supplier in the world of photolithography systems for the semiconductor industry'),
('TEAM', 'Atlassian Corp', 'Australian enterprise software company'),
('ADSK', 'Autodesk Inc', 'American multinational software corporation');



-- Insert into portfolio table
INSERT INTO portfolio (id, user_id, name, description, created_at, updated_at)
VALUES (1, 1, 'Hisse Senedi Portfoyum', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert into allocation table
INSERT INTO allocation (portfolio_id, asset_id, target_percentage)
VALUES
    (1, 1, 20.00),
    (1, 2, 30.00),
    (1, 3, 10.00),
    (1, 4, 5.00),
    (1, 5, 5.00),
    (1, 6, 20.00),
    (1, 7, 2.00),
    (1, 8, 2.00),
    (1, 9, 2.00),
    (1, 10, 4.00);

COMMIT;
